export { default as SignUp } from './SignUp/SignUp'
export { default as SignIn } from './SignIn/SignIn'
export { default as Result } from './Result/Result'
export { default as Question } from './Question/Question'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as ResumeQuestion } from './ResumeQuestion/ResumeQuestion'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword'
