export * from './SignUp/SignUp'
export * from './SignIn/SignIn'
export * from './Result/Result'
export * from './Question/Question'
export * from './NotFound/NotFound'
export * from './Dashboard/Dashboard'
export * from './ResumeQuestion/ResumeQuestion'
export * from './ForgotPassword/ForgotPassword'
